#!/usr/bin/env python3
"""Android string resources from i18n/strings.json (read-only: never writes into i18n/ or site/).

Usage: python3 tools/build-app-strings.py <out-res-dir> <langs, e.g. he,en,ru,ka>
Writes <out>/values/strings.xml (Hebrew, the default), <out>/values-<lang>/strings.xml for the others, and
<out>/xml/locales_config.xml listing exactly those languages.

- Keys: "area.name" becomes "area_name" (game.descent.again -> game_descent_again).
- Placeholders: {name} becomes %N$s, numbered by their first appearance in the Hebrew text, the same numbers in
  every language (a translation may move them). The app passes arguments in the Hebrew order.
- Plurals (CLDR forms per language) become <plurals>.
- A language whose strings still wait for a native speaker ("check" in i18n/strings.json, see i18n/REVIEW.md) is
  refused unless --unreviewed is given: test builds may carry it, store builds may not.
"""
import json
import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
PH = re.compile(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}")


def name(key):
    n = key.replace(".", "_")
    if not re.fullmatch(r"[a-z][a-z0-9_]*", n):
        raise SystemExit(f"bad key for Android: {key}")
    return n


def order(he):
    seen = []
    for form in (he.values() if isinstance(he, dict) else [he]):
        for p in PH.findall(form):
            if p not in seen:
                seen.append(p)
    return {p: i + 1 for i, p in enumerate(seen)}


def android(text, idx):
    """One text as an Android resource value."""
    has = bool(PH.search(text))
    if has:
        text = text.replace("%", "%%")
    out = escape(text).replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"').replace("\n", "\\n")
    if out[:1] in "@?":
        out = "\\" + out
    out = PH.sub(lambda m: f"%{idx[m.group(1)]}$s", out)
    return out, has


def file_for(lang, strings):
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             '<!-- Generated by tools/build-app-strings.py from i18n/strings.json. Do not edit: edit i18n/strings.json. -->',
             '<resources>',
             f'    <string name="lang" translatable="false">{lang}</string>']
    for key, e in strings.items():
        idx = order(e["he"])
        v = e[lang]
        if isinstance(v, dict):
            lines.append(f'    <plurals name="{name(key)}">')
            for q, form in v.items():
                text, _ = android(form, idx)
                lines.append(f'        <item quantity="{q}">{text}</item>')
            lines.append('    </plurals>')
        else:
            text, has = android(v, idx)
            fmt = '' if has or "%" not in v else ' formatted="false"'
            lines.append(f'    <string name="{name(key)}"{fmt}>{text}</string>')
    lines.append('</resources>')
    return "\n".join(lines) + "\n"


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    unreviewed = "--unreviewed" in sys.argv
    out = Path(args[0]).resolve()
    langs = args[1].split(",")
    data = json.loads((ROOT / "i18n/strings.json").read_text(encoding="utf-8"))
    strings = data["strings"]
    names = {}
    for key in strings:
        n = name(key)
        if n in names:
            raise SystemExit(f"{key} and {names[n]} both become {n}")
        names[n] = key
    if langs[0] != data["meta"]["source"]:
        raise SystemExit("the first language must be the source (he): it is the default values/ file")
    pending = {l for e in strings.values() for l in e.get("check", [])}
    blocked = [l for l in langs if l in pending]
    if blocked and not unreviewed:
        raise SystemExit(f"waiting for a native speaker (i18n/REVIEW.md): {blocked}. Test builds only, with --unreviewed.")
    for i, lang in enumerate(langs):
        d = out / ("values" if i == 0 else f"values-{lang}")
        d.mkdir(parents=True, exist_ok=True)
        (d / "strings.xml").write_text(file_for(lang, strings), encoding="utf-8")
    (out / "xml").mkdir(parents=True, exist_ok=True)
    (out / "xml/locales_config.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tools/build-app-strings.py: the languages of this build, for the phone\'s per-app language setting. -->\n'
        '<locale-config xmlns:android="http://schemas.android.com/apk/res/android">\n'
        + "".join(f'    <locale android:name="{l}" />\n' for l in langs)
        + '</locale-config>\n', encoding="utf-8")


if __name__ == "__main__":
    main()
