#!/usr/bin/env python3
"""Builds the privacy page of the site (site/privacy.html, served at /privacy) from docs/PRIVACY.md.

docs/PRIVACY.md stays the only source of the text (decision 33); edit it there and run this again.
The design is P1 and P2 of round 10 in the canvas (decision 36): the policy in Hebrew, English, Russian and Georgian
(decision 46) on one page, a language switch (/privacy#en, #ru, #ka open the others; with no hash, the language chosen on
the site, else Hebrew for a Hebrew browser and English for any other, as js/i18n.js picks it), the "unofficial" sign and the "in short" box under fresh snow.
Run from the repo root: python3 tools/build-privacy.py"""
import html, pathlib, re

root = pathlib.Path(__file__).resolve().parent.parent
SRC = root / 'docs/PRIVACY.md'
OUT = root / 'site/privacy.html'
MAIL = 'pinisagent@gmail.com'
# the languages, in the order of the switch: the heading of each one in docs/PRIVACY.md, the short name on its button,
# its full name for screen readers, and the label of the link back to the site's about page (common.about_settings)
LANGS = [('he', 'עברית', 'עב', 'עברית', 'אודות'), ('en', 'English', 'EN', 'English', 'About'),
         ('ru', 'Русский', 'RU', 'Русский', 'О сайте'), ('ka', 'ქართული', 'KA', 'ქართული', 'შესახებ')]
SEED = {'he': 5, 'en': 9, 'ru': 13, 'ka': 17}  # a different drift of snow for each language (drawn by site/js/snow.js)


def inline(s):
    s = html.escape(s, quote=False)
    s = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', s)
    s = re.sub(r'`(.+?)`', r'<span dir="ltr">\1</span>', s)
    s = s.replace(MAIL, f'<a href="mailto:{MAIL}" dir="ltr">{MAIL}</a>')
    return s


def blocks(text):
    """Paragraphs and lists (bulleted or numbered) from a small piece of markdown."""
    out, items, kind = [], [], None

    def flush():
        nonlocal items, kind
        if items:
            out.append(f'<{kind}>' + ''.join(f'<li>{inline(t)}</li>' for t in items) + f'</{kind}>')
        items, kind = [], None
    for line in text.strip().split('\n'):
        line = line.strip()
        m = re.match(r'^(- |\d+\. )(.*)$', line)
        if m:
            k = 'ol' if m.group(1)[0].isdigit() else 'ul'
            if kind and kind != k:
                flush()
            kind = k
            items.append(m.group(2))
        else:
            flush()
            if line:
                out.append(f'<p>{inline(line)}</p>')
    flush()
    return '\n'.join(out)


def language(md, lang):
    """One language of the policy: title, date, intro, the unofficial note, and the sections."""
    head, *secs = md.split('\n### ')
    lines = [l.strip() for l in head.strip().split('\n') if l.strip()]
    title = re.sub(r'\*\*(.+?)\*\*', r'\1', lines[0]).split(':')[0]
    date, intro, unofficial = lines[1], lines[2], lines[3]
    m = re.match(r'\*\*(.+?)\*\*\s*(.*)', unofficial)
    sections = []
    for s in secs:
        t, _, body = s.partition('\n')
        sections.append((t.strip(), blocks(body)))
    return dict(title=title, date=date, intro=inline(intro), uo_title=m.group(1).rstrip('.'), uo_text=m.group(2),
                short=sections[0], rest=sections[1:])


def section_html(p, lang):
    rtl = lang == 'he'
    rest = '\n'.join(f'<section class="pv-sec"><h2>{t}</h2>\n{b}</section>' for t, b in p['rest'])
    return f'''<article class="pv-doc" id="{lang}" lang="{lang}" dir="{'rtl' if rtl else 'ltr'}">
<h1>{p['title']}</h1>
<p class="pv-date">{p['date']}</p>
<p class="pv-intro">{p['intro']}</p>
<div class="pv-sign"><b>{p['uo_title']}</b><span>{p['uo_text']}</span></div>
<section class="pv-short" data-snow="{SEED[lang]}" data-snow-pile><h2>{p['short'][0]}</h2>
{p['short'][1]}</section>
{rest}
</article>'''


def build():
    md = SRC.read_text(encoding='utf-8')
    parts = {}
    for i, (lang, head, *_rest) in enumerate(LANGS):
        body = md.split('## ' + head, 1)[1]
        for nxt in LANGS[i + 1:]:
            body = body.split('## ' + nxt[1], 1)[0]
        parts[lang] = language(body.strip().strip('-').strip(), lang)
    back = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14"/><path d="M13 6l6 6-6 6"/></svg>'
    buttons = '\n    '.join(f'<button type="button" data-lang="{l}" aria-pressed="{str(l == "he").lower()}" lang="{l}" aria-label="{full}">{short}</button>'
                            for l, _h, short, full, _b in LANGS)
    backs = ''.join(f'<span data-back="{l}" lang="{l}"{"" if l == "he" else " hidden"}>{b}</span>' for l, _h, _s, _f, b in LANGS)
    docs = '\n'.join(section_html(parts[l], l) for l, *_ in LANGS)
    return f'''<!doctype html>
<!-- Generated by tools/build-privacy.py from docs/PRIVACY.md. Do not edit here. -->
<html lang="he" dir="rtl" class="pv">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>מדיניות פרטיות · Privacy Policy · Gudi: Gudauri Ski Map</title>
<meta name="description" content="מדיניות הפרטיות של האפליקציה והאתר. Privacy policy of the app and the website.">
<meta name="robots" content="noindex">
<meta name="theme-color" content="#EEF2F5" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0D1522" media="(prefers-color-scheme: dark)">
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Karantina:wght@700&family=IBM+Plex+Sans+Hebrew:wght@400;500;600;700&family=IBM+Plex+Sans:wght@400;600;700&family=Oswald:wght@500;600;700&family=Noto+Sans+Georgian:wdth,wght@62.5..100,400..800&display=swap">
<link rel="stylesheet" href="css/site.css">
<script src="js/prefs.js"></script>
<script src="js/telemetry.js" data-screen="privacy"></script>
<script src="js/snow.js" defer></script>
</head>
<body>
<header class="pv-top">
  <a class="pv-brand" href="/">גודאורי 2027</a>
  <div class="pv-lang" role="group" aria-label="שפה · Language">
    {buttons}
  </div>
  <a class="pv-back" href="/#about">{back}{backs}</a>
</header>
<main class="pv-main">
{docs}
<p class="pv-foot"><span dir="ltr">gudauri-ski-trip.vercel.app/privacy</span></p>
</main>
<script src="js/privacy.js"></script>
</body>
</html>
'''


if __name__ == '__main__':
    OUT.write_text(build(), encoding='utf-8')
    print('wrote', OUT.relative_to(root))
